//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aydinlik_Bilgi_Islem.Models.db
{
    using System.ComponentModel;
    public partial class Admin
    {
        [DisplayName("Kullanýcý Adý")]
        public string user { get; set; }
        [DisplayName("Sifre")]
        public string password { get; set; }
        public long id { get; set; }
    }
}
