//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aydinlik_Bilgi_Islem.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class dahiliNum
    {
        public long id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string unvan { get; set; }
        public string dahili { get; set; }
    }
}
