//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aydinlik_Bilgi_Islem.Models.db
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class GenelBilgi
    {
        [Key]
        public long id { get; set; }
        [Required]
        public string ad { get; set; }
        public string soyad { get; set; }
        public string email { get; set; }
        public Nullable<bool> islemYapildimi { get; set; }
        public string dahili { get; set; }
        public string konu { get; set; }
        [Required]
        public string sikayet { get; set; }
        public Nullable<bool> bilgisayarAcipKapama { get; set; }
        public Nullable<bool> programiAcipKapama { get; set; }
        public Nullable<bool> kablolarTakili { get; set; }
        public Nullable<bool> gucDugmesiAcikMi { get; set; }
        public string ip { get; set; }
        public string macAdres { get; set; }
    }
}
